name: zqy Library seat book


on:
  schedule:
    - cron: "50 21 * * *"
  workflow_dispatch:  # 手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # 检出代码

      - name: Set Up Python
        uses: actions/setup-python@v4  # 设置 Python 环境
        with:
          python-version: "3.9"  # 使用 Python 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # 安装脚本所需的依赖库
          
      - name: Install dependencies
        run: |
          pip install pytz

      - name: Run Library Booking Script
        run: |
          python zqy2.py
